### ISSUE TITLE
Removing a child from node that was compacted panics 

### ISSUE THREAD

**Issue by b1shan** [tchap/go-patricia#21] opened 2016-02-26 17:49 UTC
@tchap we ran into the following panic situation

```
$ go test 3debug_patricia_test.go 
--- FAIL: Test_DebugCrash (0.00s)
panic: removing non-existent child [recovered]
	panic: removing non-existent child

goroutine 5 [running]:
testing.func·006()
	/usr/local/go/src/testing/testing.go:441 +0x149
github.com/tchap/go-patricia/patricia.(*sparseChildList).remove(0x10362df0, 0x103afcb0)
	/Users/bishan/go/src/github.com/tchap/go-patricia/patricia/children.go:90 +0x25c
github.com/tchap/go-patricia/patricia.(*Trie).Delete(0x10356150, 0x10419d20, 0x18, 0x20, 0x20)
	/Users/bishan/go/src/github.com/tchap/go-patricia/patricia/patricia.go:270 +0x169
command-line-arguments.Test_DebugCrash(0x1034c0c0)
	/Users/bishan/go/src/bishan/3debug_patricia_test.go:3382 +0x20d
testing.tRunner(0x1034c0c0, 0x1db498)
	/usr/local/go/src/testing/testing.go:447 +0xab
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0x85d

goroutine 1 [chan receive]:
testing.RunTests(0x1655a4, 0x1db498, 0x1, 0x1, 0x10350001)
	/usr/local/go/src/testing/testing.go:556 +0x899
testing.(*M).Run(0x10356090, 0x1e3860)
	/usr/local/go/src/testing/testing.go:485 +0x58
main.main()
	command-line-arguments/_test/_testmain.go:52 +0x171
FAIL	command-line-arguments	0.007s
``` 
I can pass on the test case privately if you need. I could not prune the test to a small enough size and I believe I might have some sensitive data there.

The bug seems to be in the following flow:
1. delete the node
https://github.com/tchap/go-patricia/blob/master/patricia/patricia.go#L252
2. compact the node
https://github.com/tchap/go-patricia/blob/master/patricia/patricia.go#L255
3. remove children from the compacted node
https://github.com/tchap/go-patricia/blob/master/patricia/patricia.go#L270

In our debugging we found that the node is already not in the tree and we are attempting to remove it, causing a panic here:
https://github.com/tchap/go-patricia/blob/master/patricia/children.go#L90

**Comment by tchap** [comment] 2016-02-26 20:27
Will take a look when I have some time, thanks.

**Comment by tchap** [comment] 2016-03-02 15:07
Ok, the cause may be apparent from reading this:

```go
func (list *denseChildList) replace(b byte, child *Trie) {
	list.children[int(b)-list.min] = nil
	list.children[int(child.prefix[0])-list.min] = child
}
```

Actually I am not sure why it is implemented like this, have to dig deeper. I guess the panic happens when `b != child.prefix[0]`. Haven't touched this package for some time, have to investigate why things are as they are :-) On top of that, the sparse mode works differently, so this is definitely weird:

```go
func (list *sparseChildList) replace(b byte, child *Trie) {
	// Seek the child and replace it.
	for i, node := range list.children {
		if node.prefix[0] == b {
			list.children[i] = child
			return
		}
	}
}
```

So, let me investigate a bit more...

**Comment by tchap** [comment] 2016-03-02 15:57
@b1shan I pushed a branch called `fix-issue-21`. Could you try whether that fixes the issue please?

**Comment by tchap** [comment] 2016-03-02 15:57
Or at least try and tell me what it does when you use it :-)

**Comment by b1shan** [comment] 2016-03-02 17:24
@tchap my test doesn't fail with `fix-issue-21` branch!

**Comment by tchap** [comment] 2016-06-04 21:35
Merged into master, finally. Sorry, forget about the issue.

**Closed by tchap** 2016-06-04 21:35 UTC
